name: Tests
on: 
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: lolpassword
        options: --health-cmd pg_isready --health-interval 10s
    steps:
    - uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install Bundler
      run: gem install bundler:2.1.4
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.22.1
    - name: Setup Rails
      env:
        RAILS_ENV: test
      run: |
        bundle install --no-deployment --jobs 4 --retry 3
        rails db:create
        rails db:migrate
        yarn --frozen-lockfile
    - name: Run Rspec Tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec spec